DELETE FROM Base_Arch
INSERT INTO base_arch SELECT (SELECT TOP 1 IdBase FROM Base WHERE Description = 'Tradicional' And [Order]=1),  (SELECT ID FROM Arch WHERE Description = 'Rígido')
INSERT INTO base_arch SELECT (SELECT TOP 1 IdBase FROM Base WHERE Description = 'Tradicional' And [Order]=1),  (SELECT ID FROM Arch WHERE Description = 'Semirígido')
INSERT INTO base_arch SELECT (SELECT TOP 1 IdBase FROM Base WHERE Description = 'Tradicional' And [Order]=1),  (SELECT ID FROM Arch WHERE Description = 'Blando')
INSERT INTO base_arch SELECT (SELECT TOP 1 IdBase FROM Base WHERE Description = 'Tradicional' And [Order]=1),  (SELECT ID FROM Arch WHERE Description = 'Rígido Alto')
INSERT INTO base_arch SELECT (SELECT TOP 1 IdBase FROM Base WHERE Description = 'Tradicional' And [Order]=1),  (SELECT ID FROM Arch WHERE Description = 'Semirígido Alto')
INSERT INTO base_arch SELECT (SELECT TOP 1 IdBase FROM Base WHERE Description = 'Tradicional' And [Order]=1),  (SELECT ID FROM Arch WHERE Description = 'Blando Alto')
INSERT INTO base_arch SELECT (SELECT TOP 1 IdBase FROM Base WHERE Description = 'Tradicional' And [Order]=1),  (SELECT ID FROM Arch WHERE Description = 'Rígido Bajo')
INSERT INTO base_arch SELECT (SELECT TOP 1 IdBase FROM Base WHERE Description = 'Tradicional' And [Order]=1),  (SELECT ID FROM Arch WHERE Description = 'Semirígido Bajo')
INSERT INTO base_arch SELECT (SELECT TOP 1 IdBase FROM Base WHERE Description = 'Tradicional' And [Order]=1),  (SELECT ID FROM Arch WHERE Description = 'Blando Bajo')
INSERT INTO base_arch SELECT (SELECT TOP 1 IdBase FROM Base WHERE Description = 'Tradicional' And [Order]=1),  (SELECT ID FROM Arch WHERE Description = 'Apoyo Total')
INSERT INTO base_arch SELECT (SELECT TOP 1 IdBase FROM Base WHERE Description = 'Tradicional' And [Order]=1),  (SELECT ID FROM Arch WHERE Description = 'Apoyo Total (Bajo)')
INSERT INTO base_arch SELECT (SELECT TOP 1 IdBase FROM Base WHERE Description = 'Tradicional' And [Order]=1),  (SELECT ID FROM Arch WHERE Description = 'Apoyo Total (Arco Debajo)')
INSERT INTO base_arch SELECT (SELECT TOP 1 IdBase FROM Base WHERE Description = 'Tradicional' And [Order]=1),  (SELECT ID FROM Arch WHERE Description = 'Semiblando')
INSERT INTO base_arch SELECT (SELECT TOP 1 IdBase FROM Base WHERE Description = 'Tradicional' And [Order]=1),  (SELECT ID FROM Arch WHERE Description = '1/4 de esfera')
INSERT INTO base_arch SELECT (SELECT TOP 1 IdBase FROM Base WHERE Description = 'Tradicional' And [Order]=1),  (SELECT ID FROM Arch WHERE Description = 'Asimetrico Rígido')
INSERT INTO base_arch SELECT (SELECT TOP 1 IdBase FROM Base WHERE Description = 'Tradicional' And [Order]=1),  (SELECT ID FROM Arch WHERE Description = 'Arco Rigido Recto 90º Casa Cuna')
INSERT INTO base_arch SELECT (SELECT TOP 1 IdBase FROM Base WHERE Description = 'Tradicional' And [Order]=1),  (SELECT ID FROM Arch WHERE Description = 'Arco Blando Recto 90º Casa Cuna')
INSERT INTO base_arch SELECT (SELECT TOP 1 IdBase FROM Base WHERE Description = 'Microcelular sin Escátola' And [Order]=5),  (SELECT ID FROM Arch WHERE Description = 'Rígido')
INSERT INTO base_arch SELECT (SELECT TOP 1 IdBase FROM Base WHERE Description = 'Microcelular sin Escátola' And [Order]=5),  (SELECT ID FROM Arch WHERE Description = 'Semirígido')
INSERT INTO base_arch SELECT (SELECT TOP 1 IdBase FROM Base WHERE Description = 'Microcelular sin Escátola' And [Order]=5),  (SELECT ID FROM Arch WHERE Description = 'Blando')
INSERT INTO base_arch SELECT (SELECT TOP 1 IdBase FROM Base WHERE Description = 'Microcelular sin Escátola' And [Order]=5),  (SELECT ID FROM Arch WHERE Description = 'Rígido Alto')
INSERT INTO base_arch SELECT (SELECT TOP 1 IdBase FROM Base WHERE Description = 'Microcelular sin Escátola' And [Order]=5),  (SELECT ID FROM Arch WHERE Description = 'Semirígido Alto')
INSERT INTO base_arch SELECT (SELECT TOP 1 IdBase FROM Base WHERE Description = 'Microcelular sin Escátola' And [Order]=5),  (SELECT ID FROM Arch WHERE Description = 'Blando Alto')
INSERT INTO base_arch SELECT (SELECT TOP 1 IdBase FROM Base WHERE Description = 'Microcelular sin Escátola' And [Order]=5),  (SELECT ID FROM Arch WHERE Description = 'Rígido Bajo')
INSERT INTO base_arch SELECT (SELECT TOP 1 IdBase FROM Base WHERE Description = 'Microcelular sin Escátola' And [Order]=5),  (SELECT ID FROM Arch WHERE Description = 'Semirígido Bajo')
INSERT INTO base_arch SELECT (SELECT TOP 1 IdBase FROM Base WHERE Description = 'Microcelular sin Escátola' And [Order]=5),  (SELECT ID FROM Arch WHERE Description = 'Blando Bajo')
INSERT INTO base_arch SELECT (SELECT TOP 1 IdBase FROM Base WHERE Description = 'Microcelular sin Escátola' And [Order]=5),  (SELECT ID FROM Arch WHERE Description = 'Apoyo Total')
INSERT INTO base_arch SELECT (SELECT TOP 1 IdBase FROM Base WHERE Description = 'Microcelular sin Escátola' And [Order]=5),  (SELECT ID FROM Arch WHERE Description = 'Apoyo Total (Bajo)')
INSERT INTO base_arch SELECT (SELECT TOP 1 IdBase FROM Base WHERE Description = 'Microcelular sin Escátola' And [Order]=5),  (SELECT ID FROM Arch WHERE Description = 'Apoyo Total (Arco Debajo)')
INSERT INTO base_arch SELECT (SELECT TOP 1 IdBase FROM Base WHERE Description = 'Microcelular sin Escátola' And [Order]=5),  (SELECT ID FROM Arch WHERE Description = 'Semiblando')
INSERT INTO base_arch SELECT (SELECT TOP 1 IdBase FROM Base WHERE Description = 'Microcelular sin Escátola' And [Order]=5),  (SELECT ID FROM Arch WHERE Description = '1/4 de esfera')
INSERT INTO base_arch SELECT (SELECT TOP 1 IdBase FROM Base WHERE Description = 'Microcelular sin Escátola' And [Order]=5),  (SELECT ID FROM Arch WHERE Description = 'Asimetrico Rígido')
INSERT INTO base_arch SELECT (SELECT TOP 1 IdBase FROM Base WHERE Description = 'Microcelular sin Escátola' And [Order]=5),  (SELECT ID FROM Arch WHERE Description = 'Arco Rigido Recto 90º Casa Cuna')
INSERT INTO base_arch SELECT (SELECT TOP 1 IdBase FROM Base WHERE Description = 'Microcelular sin Escátola' And [Order]=5),  (SELECT ID FROM Arch WHERE Description = 'Arco Blando Recto 90º Casa Cuna')
INSERT INTO base_arch SELECT (SELECT TOP 1 IdBase FROM Base WHERE Description = 'Microcelular con Escátola' And [Order]=4),  (SELECT ID FROM Arch WHERE Description = 'Blando')
INSERT INTO base_arch SELECT (SELECT TOP 1 IdBase FROM Base WHERE Description = 'Microcelular con Escátola' And [Order]=4),  (SELECT ID FROM Arch WHERE Description = 'Blando Alto')
INSERT INTO base_arch SELECT (SELECT TOP 1 IdBase FROM Base WHERE Description = 'Microcelular con Escátola' And [Order]=4),  (SELECT ID FROM Arch WHERE Description = 'Blando Bajo')
INSERT INTO base_arch SELECT (SELECT TOP 1 IdBase FROM Base WHERE Description = 'Microcelular con Escátola' And [Order]=4),  (SELECT ID FROM Arch WHERE Description = 'Apoyo Total')
INSERT INTO base_arch SELECT (SELECT TOP 1 IdBase FROM Base WHERE Description = 'Microcelular con Escátola' And [Order]=4),  (SELECT ID FROM Arch WHERE Description = 'Apoyo Total (Bajo)')
INSERT INTO base_arch SELECT (SELECT TOP 1 IdBase FROM Base WHERE Description = 'Microcelular con Escátola' And [Order]=4),  (SELECT ID FROM Arch WHERE Description = 'Apoyo Total (Arco Debajo)')
INSERT INTO base_arch SELECT (SELECT TOP 1 IdBase FROM Base WHERE Description = 'Gel Polímero sin Escátola' And [Order]=7),  (SELECT ID FROM Arch WHERE Description = 'Blando')
INSERT INTO base_arch SELECT (SELECT TOP 1 IdBase FROM Base WHERE Description = 'Gel Polímero sin Escátola' And [Order]=7),  (SELECT ID FROM Arch WHERE Description = 'Blando Alto')
INSERT INTO base_arch SELECT (SELECT TOP 1 IdBase FROM Base WHERE Description = 'Gel Polímero sin Escátola' And [Order]=7),  (SELECT ID FROM Arch WHERE Description = 'Blando Bajo')
INSERT INTO base_arch SELECT (SELECT TOP 1 IdBase FROM Base WHERE Description = 'Gel Polímero sin Escátola' And [Order]=7),  (SELECT ID FROM Arch WHERE Description = 'Apoyo Total')
INSERT INTO base_arch SELECT (SELECT TOP 1 IdBase FROM Base WHERE Description = 'Celuloide (Finita)' And [Order]=21),  (SELECT ID FROM Arch WHERE Description = 'Rígido')
INSERT INTO base_arch SELECT (SELECT TOP 1 IdBase FROM Base WHERE Description = 'Celuloide (Finita)' And [Order]=21),  (SELECT ID FROM Arch WHERE Description = 'Semirígido')
INSERT INTO base_arch SELECT (SELECT TOP 1 IdBase FROM Base WHERE Description = 'Celuloide (Finita)' And [Order]=21),  (SELECT ID FROM Arch WHERE Description = 'Blando')
INSERT INTO base_arch SELECT (SELECT TOP 1 IdBase FROM Base WHERE Description = 'Celuloide (Finita)' And [Order]=21),  (SELECT ID FROM Arch WHERE Description = 'Rígido Alto')
INSERT INTO base_arch SELECT (SELECT TOP 1 IdBase FROM Base WHERE Description = 'Celuloide (Finita)' And [Order]=21),  (SELECT ID FROM Arch WHERE Description = 'Semirígido Alto')
INSERT INTO base_arch SELECT (SELECT TOP 1 IdBase FROM Base WHERE Description = 'Celuloide (Finita)' And [Order]=21),  (SELECT ID FROM Arch WHERE Description = 'Blando Alto')
INSERT INTO base_arch SELECT (SELECT TOP 1 IdBase FROM Base WHERE Description = 'Celuloide (Finita)' And [Order]=21),  (SELECT ID FROM Arch WHERE Description = 'Rígido Bajo')
INSERT INTO base_arch SELECT (SELECT TOP 1 IdBase FROM Base WHERE Description = 'Celuloide (Finita)' And [Order]=21),  (SELECT ID FROM Arch WHERE Description = 'Semirígido Bajo')
INSERT INTO base_arch SELECT (SELECT TOP 1 IdBase FROM Base WHERE Description = 'Celuloide (Finita)' And [Order]=21),  (SELECT ID FROM Arch WHERE Description = 'Blando Bajo')
INSERT INTO base_arch SELECT (SELECT TOP 1 IdBase FROM Base WHERE Description = 'Celuloide (Finita)' And [Order]=21),  (SELECT ID FROM Arch WHERE Description = 'Apoyo Total')
INSERT INTO base_arch SELECT (SELECT TOP 1 IdBase FROM Base WHERE Description = 'Celuloide (Finita)' And [Order]=21),  (SELECT ID FROM Arch WHERE Description = 'Apoyo Total (Bajo)')
INSERT INTO base_arch SELECT (SELECT TOP 1 IdBase FROM Base WHERE Description = 'Celuloide (Finita)' And [Order]=21),  (SELECT ID FROM Arch WHERE Description = 'Apoyo Total (Arco Debajo)')
INSERT INTO base_arch SELECT (SELECT TOP 1 IdBase FROM Base WHERE Description = 'Celuloide (Finita)' And [Order]=21),  (SELECT ID FROM Arch WHERE Description = 'Semiblando')
INSERT INTO base_arch SELECT (SELECT TOP 1 IdBase FROM Base WHERE Description = 'Celuloide (Finita)' And [Order]=21),  (SELECT ID FROM Arch WHERE Description = '1/4 de esfera')
INSERT INTO base_arch SELECT (SELECT TOP 1 IdBase FROM Base WHERE Description = 'Celuloide (Finita)' And [Order]=21),  (SELECT ID FROM Arch WHERE Description = 'Asimetrico Rígido')
INSERT INTO base_arch SELECT (SELECT TOP 1 IdBase FROM Base WHERE Description = 'Celuloide (Finita)' And [Order]=21),  (SELECT ID FROM Arch WHERE Description = 'Arco Rigido Recto 90º Casa Cuna')
INSERT INTO base_arch SELECT (SELECT TOP 1 IdBase FROM Base WHERE Description = 'Celuloide (Finita)' And [Order]=21),  (SELECT ID FROM Arch WHERE Description = 'Arco Blando Recto 90º Casa Cuna')
INSERT INTO base_arch SELECT (SELECT TOP 1 IdBase FROM Base WHERE Description = 'BlueFlex s/escatola' And [Order]=29),  (SELECT ID FROM Arch WHERE Description = 'Rígido')
INSERT INTO base_arch SELECT (SELECT TOP 1 IdBase FROM Base WHERE Description = 'BlueFlex s/escatola' And [Order]=29),  (SELECT ID FROM Arch WHERE Description = 'Semirígido')
INSERT INTO base_arch SELECT (SELECT TOP 1 IdBase FROM Base WHERE Description = 'BlueFlex s/escatola' And [Order]=29),  (SELECT ID FROM Arch WHERE Description = 'Blando')
INSERT INTO base_arch SELECT (SELECT TOP 1 IdBase FROM Base WHERE Description = 'BlueFlex s/escatola' And [Order]=29),  (SELECT ID FROM Arch WHERE Description = 'Rígido Alto')
INSERT INTO base_arch SELECT (SELECT TOP 1 IdBase FROM Base WHERE Description = 'BlueFlex s/escatola' And [Order]=29),  (SELECT ID FROM Arch WHERE Description = 'Semirígido Alto')
INSERT INTO base_arch SELECT (SELECT TOP 1 IdBase FROM Base WHERE Description = 'BlueFlex s/escatola' And [Order]=29),  (SELECT ID FROM Arch WHERE Description = 'Blando Alto')
INSERT INTO base_arch SELECT (SELECT TOP 1 IdBase FROM Base WHERE Description = 'BlueFlex s/escatola' And [Order]=29),  (SELECT ID FROM Arch WHERE Description = 'Rígido Bajo')
INSERT INTO base_arch SELECT (SELECT TOP 1 IdBase FROM Base WHERE Description = 'BlueFlex s/escatola' And [Order]=29),  (SELECT ID FROM Arch WHERE Description = 'Semirígido Bajo')
INSERT INTO base_arch SELECT (SELECT TOP 1 IdBase FROM Base WHERE Description = 'BlueFlex s/escatola' And [Order]=29),  (SELECT ID FROM Arch WHERE Description = 'Blando Bajo')
INSERT INTO base_arch SELECT (SELECT TOP 1 IdBase FROM Base WHERE Description = 'BlueFlex s/escatola' And [Order]=29),  (SELECT ID FROM Arch WHERE Description = 'Apoyo Total')
INSERT INTO base_arch SELECT (SELECT TOP 1 IdBase FROM Base WHERE Description = 'BlueFlex s/escatola' And [Order]=29),  (SELECT ID FROM Arch WHERE Description = 'Apoyo Total (Bajo)')
INSERT INTO base_arch SELECT (SELECT TOP 1 IdBase FROM Base WHERE Description = 'BlueFlex s/escatola' And [Order]=29),  (SELECT ID FROM Arch WHERE Description = 'Apoyo Total (Arco Debajo)')
INSERT INTO base_arch SELECT (SELECT TOP 1 IdBase FROM Base WHERE Description = 'BlueFlex s/escatola' And [Order]=29),  (SELECT ID FROM Arch WHERE Description = 'Semiblando')
INSERT INTO base_arch SELECT (SELECT TOP 1 IdBase FROM Base WHERE Description = 'BlueFlex s/escatola' And [Order]=29),  (SELECT ID FROM Arch WHERE Description = '1/4 de esfera')
INSERT INTO base_arch SELECT (SELECT TOP 1 IdBase FROM Base WHERE Description = 'BlueFlex s/escatola' And [Order]=29),  (SELECT ID FROM Arch WHERE Description = 'Asimetrico Rígido')
INSERT INTO base_arch SELECT (SELECT TOP 1 IdBase FROM Base WHERE Description = 'BlueFlex s/escatola' And [Order]=29),  (SELECT ID FROM Arch WHERE Description = 'Arco Rigido Recto 90º Casa Cuna')
INSERT INTO base_arch SELECT (SELECT TOP 1 IdBase FROM Base WHERE Description = 'BlueFlex s/escatola' And [Order]=29),  (SELECT ID FROM Arch WHERE Description = 'Arco Blando Recto 90º Casa Cuna')
INSERT INTO base_arch SELECT (SELECT TOP 1 IdBase FROM Base WHERE Description = 'BlueFlex c/Esctola' And [Order]=30),  (SELECT ID FROM Arch WHERE Description = 'Blando')
INSERT INTO base_arch SELECT (SELECT TOP 1 IdBase FROM Base WHERE Description = 'BlueFlex c/Esctola' And [Order]=30),  (SELECT ID FROM Arch WHERE Description = 'Blando Alto')
INSERT INTO base_arch SELECT (SELECT TOP 1 IdBase FROM Base WHERE Description = 'BlueFlex c/Esctola' And [Order]=30),  (SELECT ID FROM Arch WHERE Description = 'Blando Bajo')
INSERT INTO base_arch SELECT (SELECT TOP 1 IdBase FROM Base WHERE Description = 'BlueFlex c/Esctola' And [Order]=30),  (SELECT ID FROM Arch WHERE Description = 'Apoyo Total')
INSERT INTO base_arch SELECT (SELECT TOP 1 IdBase FROM Base WHERE Description = 'BlueFlex c/Esctola' And [Order]=30),  (SELECT ID FROM Arch WHERE Description = 'Apoyo Total (Bajo)')
INSERT INTO base_arch SELECT (SELECT TOP 1 IdBase FROM Base WHERE Description = 'BlueFlex c/Esctola' And [Order]=30),  (SELECT ID FROM Arch WHERE Description = 'Apoyo Total (Arco Debajo)')
INSERT INTO base_arch SELECT (SELECT TOP 1 IdBase FROM Base WHERE Description = '3D' And [Order]=28),  (SELECT ID FROM Arch WHERE Description = 'Rígido')
INSERT INTO base_arch SELECT (SELECT TOP 1 IdBase FROM Base WHERE Description = '3D' And [Order]=28),  (SELECT ID FROM Arch WHERE Description = 'Semirígido')
INSERT INTO base_arch SELECT (SELECT TOP 1 IdBase FROM Base WHERE Description = '3D' And [Order]=28),  (SELECT ID FROM Arch WHERE Description = 'Blando')
INSERT INTO base_arch SELECT (SELECT TOP 1 IdBase FROM Base WHERE Description = '3D' And [Order]=28),  (SELECT ID FROM Arch WHERE Description = 'Rígido Alto')
INSERT INTO base_arch SELECT (SELECT TOP 1 IdBase FROM Base WHERE Description = '3D' And [Order]=28),  (SELECT ID FROM Arch WHERE Description = 'Semirígido Alto')
INSERT INTO base_arch SELECT (SELECT TOP 1 IdBase FROM Base WHERE Description = '3D' And [Order]=28),  (SELECT ID FROM Arch WHERE Description = 'Blando Alto')
INSERT INTO base_arch SELECT (SELECT TOP 1 IdBase FROM Base WHERE Description = '3D' And [Order]=28),  (SELECT ID FROM Arch WHERE Description = 'Rígido Bajo')
INSERT INTO base_arch SELECT (SELECT TOP 1 IdBase FROM Base WHERE Description = '3D' And [Order]=28),  (SELECT ID FROM Arch WHERE Description = 'Semirígido Bajo')
INSERT INTO base_arch SELECT (SELECT TOP 1 IdBase FROM Base WHERE Description = '3D' And [Order]=28),  (SELECT ID FROM Arch WHERE Description = 'Blando Bajo')
INSERT INTO base_arch SELECT (SELECT TOP 1 IdBase FROM Base WHERE Description = '3D' And [Order]=28),  (SELECT ID FROM Arch WHERE Description = 'Apoyo Total')
INSERT INTO base_arch SELECT (SELECT TOP 1 IdBase FROM Base WHERE Description = '3D' And [Order]=28),  (SELECT ID FROM Arch WHERE Description = 'Apoyo Total (Bajo)')
INSERT INTO base_arch SELECT (SELECT TOP 1 IdBase FROM Base WHERE Description = '3D' And [Order]=28),  (SELECT ID FROM Arch WHERE Description = 'Apoyo Total (Arco Debajo)')
INSERT INTO base_arch SELECT (SELECT TOP 1 IdBase FROM Base WHERE Description = '3D' And [Order]=28),  (SELECT ID FROM Arch WHERE Description = 'Semiblando')
INSERT INTO base_arch SELECT (SELECT TOP 1 IdBase FROM Base WHERE Description = 'Polifibra' And [Order]=23),  (SELECT ID FROM Arch WHERE Description = 'Rígido')
INSERT INTO base_arch SELECT (SELECT TOP 1 IdBase FROM Base WHERE Description = 'Polifibra' And [Order]=23),  (SELECT ID FROM Arch WHERE Description = 'Semirígido')
INSERT INTO base_arch SELECT (SELECT TOP 1 IdBase FROM Base WHERE Description = 'Polifibra' And [Order]=23),  (SELECT ID FROM Arch WHERE Description = 'Blando')
INSERT INTO base_arch SELECT (SELECT TOP 1 IdBase FROM Base WHERE Description = 'Polifibra' And [Order]=23),  (SELECT ID FROM Arch WHERE Description = 'Rígido Alto')
INSERT INTO base_arch SELECT (SELECT TOP 1 IdBase FROM Base WHERE Description = 'Polifibra' And [Order]=23),  (SELECT ID FROM Arch WHERE Description = 'Semirígido Alto')
INSERT INTO base_arch SELECT (SELECT TOP 1 IdBase FROM Base WHERE Description = 'Polifibra' And [Order]=23),  (SELECT ID FROM Arch WHERE Description = 'Blando Alto')
INSERT INTO base_arch SELECT (SELECT TOP 1 IdBase FROM Base WHERE Description = 'Polifibra' And [Order]=23),  (SELECT ID FROM Arch WHERE Description = 'Rígido Bajo')
INSERT INTO base_arch SELECT (SELECT TOP 1 IdBase FROM Base WHERE Description = 'Polifibra' And [Order]=23),  (SELECT ID FROM Arch WHERE Description = 'Semirígido Bajo')
INSERT INTO base_arch SELECT (SELECT TOP 1 IdBase FROM Base WHERE Description = 'Polifibra' And [Order]=23),  (SELECT ID FROM Arch WHERE Description = 'Blando Bajo')
INSERT INTO base_arch SELECT (SELECT TOP 1 IdBase FROM Base WHERE Description = 'Polifibra' And [Order]=23),  (SELECT ID FROM Arch WHERE Description = 'Semiblando')
INSERT INTO base_arch SELECT (SELECT TOP 1 IdBase FROM Base WHERE Description = 'PPS' And [Order]=22),  (SELECT ID FROM Arch WHERE Description = 'Blando')
INSERT INTO base_arch SELECT (SELECT TOP 1 IdBase FROM Base WHERE Description = 'PPS' And [Order]=22),  (SELECT ID FROM Arch WHERE Description = 'Blando Alto')
INSERT INTO base_arch SELECT (SELECT TOP 1 IdBase FROM Base WHERE Description = 'PPS' And [Order]=22),  (SELECT ID FROM Arch WHERE Description = 'Blando Bajo')
INSERT INTO base_arch SELECT (SELECT TOP 1 IdBase FROM Base WHERE Description = 'PPS' And [Order]=22),  (SELECT ID FROM Arch WHERE Description = 'Apoyo Total')
INSERT INTO base_arch SELECT (SELECT TOP 1 IdBase FROM Base WHERE Description = 'Talon reforzado' And [Order]=2),  (SELECT ID FROM Arch WHERE Description = 'Rígido')
INSERT INTO base_arch SELECT (SELECT TOP 1 IdBase FROM Base WHERE Description = 'Talon reforzado' And [Order]=2),  (SELECT ID FROM Arch WHERE Description = 'Semirígido')
INSERT INTO base_arch SELECT (SELECT TOP 1 IdBase FROM Base WHERE Description = 'Talon reforzado' And [Order]=2),  (SELECT ID FROM Arch WHERE Description = 'Blando')
INSERT INTO base_arch SELECT (SELECT TOP 1 IdBase FROM Base WHERE Description = 'Talon reforzado' And [Order]=2),  (SELECT ID FROM Arch WHERE Description = 'Rígido Alto')
INSERT INTO base_arch SELECT (SELECT TOP 1 IdBase FROM Base WHERE Description = 'Talon reforzado' And [Order]=2),  (SELECT ID FROM Arch WHERE Description = 'Semirígido Alto')
INSERT INTO base_arch SELECT (SELECT TOP 1 IdBase FROM Base WHERE Description = 'Talon reforzado' And [Order]=2),  (SELECT ID FROM Arch WHERE Description = 'Blando Alto')
INSERT INTO base_arch SELECT (SELECT TOP 1 IdBase FROM Base WHERE Description = 'Talon reforzado' And [Order]=2),  (SELECT ID FROM Arch WHERE Description = 'Rígido Bajo')
INSERT INTO base_arch SELECT (SELECT TOP 1 IdBase FROM Base WHERE Description = 'Talon reforzado' And [Order]=2),  (SELECT ID FROM Arch WHERE Description = 'Semirígido Bajo')
INSERT INTO base_arch SELECT (SELECT TOP 1 IdBase FROM Base WHERE Description = 'Talon reforzado' And [Order]=2),  (SELECT ID FROM Arch WHERE Description = 'Blando Bajo')
INSERT INTO base_arch SELECT (SELECT TOP 1 IdBase FROM Base WHERE Description = 'Talon reforzado' And [Order]=2),  (SELECT ID FROM Arch WHERE Description = 'Apoyo Total')
INSERT INTO base_arch SELECT (SELECT TOP 1 IdBase FROM Base WHERE Description = 'Talon reforzado' And [Order]=2),  (SELECT ID FROM Arch WHERE Description = 'Apoyo Total (Bajo)')
INSERT INTO base_arch SELECT (SELECT TOP 1 IdBase FROM Base WHERE Description = 'Talon reforzado' And [Order]=2),  (SELECT ID FROM Arch WHERE Description = 'Apoyo Total (Arco Debajo)')
INSERT INTO base_arch SELECT (SELECT TOP 1 IdBase FROM Base WHERE Description = 'Talon reforzado' And [Order]=2),  (SELECT ID FROM Arch WHERE Description = 'Semiblando')
INSERT INTO base_arch SELECT (SELECT TOP 1 IdBase FROM Base WHERE Description = 'Talon reforzado' And [Order]=2),  (SELECT ID FROM Arch WHERE Description = '1/4 de esfera')
INSERT INTO base_arch SELECT (SELECT TOP 1 IdBase FROM Base WHERE Description = 'Talon reforzado' And [Order]=2),  (SELECT ID FROM Arch WHERE Description = 'Asimetrico Rígido')
INSERT INTO base_arch SELECT (SELECT TOP 1 IdBase FROM Base WHERE Description = 'Talon reforzado' And [Order]=2),  (SELECT ID FROM Arch WHERE Description = 'Arco Rigido Recto 90º Casa Cuna')
INSERT INTO base_arch SELECT (SELECT TOP 1 IdBase FROM Base WHERE Description = 'Talon reforzado' And [Order]=2),  (SELECT ID FROM Arch WHERE Description = 'Arco Blando Recto 90º Casa Cuna')

INSERT INTO base_arch SELECT (SELECT TOP 1 IdBase FROM Base WHERE Description = 'Triple Densidad' And [Order]=31),  (SELECT ID FROM Arch WHERE Description = 'Rígido')
INSERT INTO base_arch SELECT (SELECT TOP 1 IdBase FROM Base WHERE Description = 'Triple Densidad' And [Order]=31),  (SELECT ID FROM Arch WHERE Description = 'Semirígido')
INSERT INTO base_arch SELECT (SELECT TOP 1 IdBase FROM Base WHERE Description = 'Triple Densidad' And [Order]=31),  (SELECT ID FROM Arch WHERE Description = 'Blando')
INSERT INTO base_arch SELECT (SELECT TOP 1 IdBase FROM Base WHERE Description = 'Triple Densidad' And [Order]=31),  (SELECT ID FROM Arch WHERE Description = 'Rígido Alto')
INSERT INTO base_arch SELECT (SELECT TOP 1 IdBase FROM Base WHERE Description = 'Triple Densidad' And [Order]=31),  (SELECT ID FROM Arch WHERE Description = 'Semirígido Alto')
INSERT INTO base_arch SELECT (SELECT TOP 1 IdBase FROM Base WHERE Description = 'Triple Densidad' And [Order]=31),  (SELECT ID FROM Arch WHERE Description = 'Blando Alto')
INSERT INTO base_arch SELECT (SELECT TOP 1 IdBase FROM Base WHERE Description = 'Triple Densidad' And [Order]=31),  (SELECT ID FROM Arch WHERE Description = 'Rígido Bajo')
INSERT INTO base_arch SELECT (SELECT TOP 1 IdBase FROM Base WHERE Description = 'Triple Densidad' And [Order]=31),  (SELECT ID FROM Arch WHERE Description = 'Semirígido Bajo')
INSERT INTO base_arch SELECT (SELECT TOP 1 IdBase FROM Base WHERE Description = 'Triple Densidad' And [Order]=31),  (SELECT ID FROM Arch WHERE Description = 'Blando Bajo')
INSERT INTO base_arch SELECT (SELECT TOP 1 IdBase FROM Base WHERE Description = 'Triple Densidad' And [Order]=31),  (SELECT ID FROM Arch WHERE Description = 'Apoyo Total')
INSERT INTO base_arch SELECT (SELECT TOP 1 IdBase FROM Base WHERE Description = 'Triple Densidad' And [Order]=31),  (SELECT ID FROM Arch WHERE Description = 'Apoyo Total (Bajo)')
INSERT INTO base_arch SELECT (SELECT TOP 1 IdBase FROM Base WHERE Description = 'Triple Densidad' And [Order]=31),  (SELECT ID FROM Arch WHERE Description = 'Apoyo Total (Arco Debajo)')
INSERT INTO base_arch SELECT (SELECT TOP 1 IdBase FROM Base WHERE Description = 'Triple Densidad' And [Order]=31),  (SELECT ID FROM Arch WHERE Description = 'Semiblando')
INSERT INTO base_arch SELECT (SELECT TOP 1 IdBase FROM Base WHERE Description = 'Triple Densidad' And [Order]=31),  (SELECT ID FROM Arch WHERE Description = '1/4 de esfera')
INSERT INTO base_arch SELECT (SELECT TOP 1 IdBase FROM Base WHERE Description = 'Triple Densidad' And [Order]=31),  (SELECT ID FROM Arch WHERE Description = 'Asimetrico Rígido')
INSERT INTO base_arch SELECT (SELECT TOP 1 IdBase FROM Base WHERE Description = 'Triple Densidad' And [Order]=31),  (SELECT ID FROM Arch WHERE Description = 'Arco Rigido Recto 90º Casa Cuna')
INSERT INTO base_arch SELECT (SELECT TOP 1 IdBase FROM Base WHERE Description = 'Triple Densidad' And [Order]=31),  (SELECT ID FROM Arch WHERE Description = 'Arco Blando Recto 90º Casa Cuna')
