INSERT INTO Base_Shape SELECT (SELECT TOP 1  IdBase FROM  Base WHERE Description = 'Tradicional' And [Order]=1),  (SELECT IdShape FROM Shape WHERE Description = 'Neutro')
INSERT INTO Base_Shape SELECT (SELECT TOP 1  IdBase FROM  Base WHERE Description = 'Tradicional' And [Order]=1),  (SELECT IdShape FROM Shape WHERE Description = 'H10')
INSERT INTO Base_Shape SELECT (SELECT TOP 1  IdBase FROM  Base WHERE Description = 'Tradicional' And [Order]=1),  (SELECT IdShape FROM Shape WHERE Description = 'Horma Ancha')
INSERT INTO Base_Shape SELECT (SELECT TOP 1  IdBase FROM  Base WHERE Description = 'Tradicional' And [Order]=1),  (SELECT IdShape FROM Shape WHERE Description = 'Evertido')
INSERT INTO Base_Shape SELECT (SELECT TOP 1  IdBase FROM  Base WHERE Description = 'Tradicional' And [Order]=1),  (SELECT IdShape FROM Shape WHERE Description = 'Recto')
INSERT INTO Base_Shape SELECT (SELECT TOP 1  IdBase FROM  Base WHERE Description = 'Tradicional' And [Order]=1),  (SELECT IdShape FROM Shape WHERE Description = 'Deportiva')
INSERT INTO Base_Shape SELECT (SELECT TOP 1  IdBase FROM  Base WHERE Description = 'Tradicional' And [Order]=1),  (SELECT IdShape FROM Shape WHERE Description = 'Florentina')
INSERT INTO Base_Shape SELECT (SELECT TOP 1  IdBase FROM  Base WHERE Description = 'Tradicional' And [Order]=1),  (SELECT IdShape FROM Shape WHERE Description = 'Canadiense')
INSERT INTO Base_Shape SELECT (SELECT TOP 1  IdBase FROM  Base WHERE Description = 'Tradicional' And [Order]=1),  (SELECT IdShape FROM Shape WHERE Description = 'H45')
INSERT INTO Base_Shape SELECT (SELECT TOP 1  IdBase FROM  Base WHERE Description = 'Microcelular sin Escátola' And [Order]=5),  (SELECT IdShape FROM Shape WHERE Description = 'Neutro')
INSERT INTO Base_Shape SELECT (SELECT TOP 1  IdBase FROM  Base WHERE Description = 'Microcelular sin Escátola' And [Order]=5),  (SELECT IdShape FROM Shape WHERE Description = 'H10')
INSERT INTO Base_Shape SELECT (SELECT TOP 1  IdBase FROM  Base WHERE Description = 'Microcelular sin Escátola' And [Order]=5),  (SELECT IdShape FROM Shape WHERE Description = 'Horma Ancha')
INSERT INTO Base_Shape SELECT (SELECT TOP 1  IdBase FROM  Base WHERE Description = 'Microcelular sin Escátola' And [Order]=5),  (SELECT IdShape FROM Shape WHERE Description = 'Evertido')
INSERT INTO Base_Shape SELECT (SELECT TOP 1  IdBase FROM  Base WHERE Description = 'Microcelular sin Escátola' And [Order]=5),  (SELECT IdShape FROM Shape WHERE Description = 'Recto')
INSERT INTO Base_Shape SELECT (SELECT TOP 1  IdBase FROM  Base WHERE Description = 'Microcelular sin Escátola' And [Order]=5),  (SELECT IdShape FROM Shape WHERE Description = 'Deportiva')
INSERT INTO Base_Shape SELECT (SELECT TOP 1  IdBase FROM  Base WHERE Description = 'Microcelular sin Escátola' And [Order]=5),  (SELECT IdShape FROM Shape WHERE Description = 'Florentina')
INSERT INTO Base_Shape SELECT (SELECT TOP 1  IdBase FROM  Base WHERE Description = 'Microcelular sin Escátola' And [Order]=5),  (SELECT IdShape FROM Shape WHERE Description = 'Canadiense')
INSERT INTO Base_Shape SELECT (SELECT TOP 1  IdBase FROM  Base WHERE Description = 'Microcelular sin Escátola' And [Order]=5),  (SELECT IdShape FROM Shape WHERE Description = 'H45')
INSERT INTO Base_Shape SELECT (SELECT TOP 1  IdBase FROM  Base WHERE Description = 'Microcelular con Escátola' And [Order]=4),  (SELECT IdShape FROM Shape WHERE Description = 'Neutro')
INSERT INTO Base_Shape SELECT (SELECT TOP 1  IdBase FROM  Base WHERE Description = 'Microcelular con Escátola' And [Order]=4),  (SELECT IdShape FROM Shape WHERE Description = 'Deportiva')
INSERT INTO Base_Shape SELECT (SELECT TOP 1  IdBase FROM  Base WHERE Description = 'Gel Polímero sin Escátola' And [Order]=7),  (SELECT IdShape FROM Shape WHERE Description = 'Neutro')
INSERT INTO Base_Shape SELECT (SELECT TOP 1  IdBase FROM  Base WHERE Description = 'Gel Polímero sin Escátola' And [Order]=7),  (SELECT IdShape FROM Shape WHERE Description = 'H10')
INSERT INTO Base_Shape SELECT (SELECT TOP 1  IdBase FROM  Base WHERE Description = 'Gel Polímero sin Escátola' And [Order]=7),  (SELECT IdShape FROM Shape WHERE Description = 'Horma Ancha')
INSERT INTO Base_Shape SELECT (SELECT TOP 1  IdBase FROM  Base WHERE Description = 'Gel Polímero sin Escátola' And [Order]=7),  (SELECT IdShape FROM Shape WHERE Description = 'Evertido')
INSERT INTO Base_Shape SELECT (SELECT TOP 1  IdBase FROM  Base WHERE Description = 'Gel Polímero sin Escátola' And [Order]=7),  (SELECT IdShape FROM Shape WHERE Description = 'Recto')
INSERT INTO Base_Shape SELECT (SELECT TOP 1  IdBase FROM  Base WHERE Description = 'Gel Polímero sin Escátola' And [Order]=7),  (SELECT IdShape FROM Shape WHERE Description = 'Deportiva')
INSERT INTO Base_Shape SELECT (SELECT TOP 1  IdBase FROM  Base WHERE Description = 'Gel Polímero sin Escátola' And [Order]=7),  (SELECT IdShape FROM Shape WHERE Description = 'Florentina')
INSERT INTO Base_Shape SELECT (SELECT TOP 1  IdBase FROM  Base WHERE Description = 'Gel Polímero sin Escátola' And [Order]=7),  (SELECT IdShape FROM Shape WHERE Description = 'Canadiense')
INSERT INTO Base_Shape SELECT (SELECT TOP 1  IdBase FROM  Base WHERE Description = 'Gel Polímero sin Escátola' And [Order]=7),  (SELECT IdShape FROM Shape WHERE Description = 'H45')
INSERT INTO Base_Shape SELECT (SELECT TOP 1  IdBase FROM  Base WHERE Description = 'Celuloide (Finita)' And [Order]=21),  (SELECT IdShape FROM Shape WHERE Description = 'Neutro')
INSERT INTO Base_Shape SELECT (SELECT TOP 1  IdBase FROM  Base WHERE Description = 'Celuloide (Finita)' And [Order]=21),  (SELECT IdShape FROM Shape WHERE Description = 'H10')
INSERT INTO Base_Shape SELECT (SELECT TOP 1  IdBase FROM  Base WHERE Description = 'Celuloide (Finita)' And [Order]=21),  (SELECT IdShape FROM Shape WHERE Description = 'Horma Ancha')
INSERT INTO Base_Shape SELECT (SELECT TOP 1  IdBase FROM  Base WHERE Description = 'Celuloide (Finita)' And [Order]=21),  (SELECT IdShape FROM Shape WHERE Description = 'Evertido')
INSERT INTO Base_Shape SELECT (SELECT TOP 1  IdBase FROM  Base WHERE Description = 'Celuloide (Finita)' And [Order]=21),  (SELECT IdShape FROM Shape WHERE Description = 'Recto')
INSERT INTO Base_Shape SELECT (SELECT TOP 1  IdBase FROM  Base WHERE Description = 'Celuloide (Finita)' And [Order]=21),  (SELECT IdShape FROM Shape WHERE Description = 'Deportiva')
INSERT INTO Base_Shape SELECT (SELECT TOP 1  IdBase FROM  Base WHERE Description = 'Celuloide (Finita)' And [Order]=21),  (SELECT IdShape FROM Shape WHERE Description = 'Florentina')
INSERT INTO Base_Shape SELECT (SELECT TOP 1  IdBase FROM  Base WHERE Description = 'Celuloide (Finita)' And [Order]=21),  (SELECT IdShape FROM Shape WHERE Description = 'Canadiense')
INSERT INTO Base_Shape SELECT (SELECT TOP 1  IdBase FROM  Base WHERE Description = 'Celuloide (Finita)' And [Order]=21),  (SELECT IdShape FROM Shape WHERE Description = 'H45')
INSERT INTO Base_Shape SELECT (SELECT TOP 1  IdBase FROM  Base WHERE Description = 'BlueFlex s/escatola' And [Order]=29),  (SELECT IdShape FROM Shape WHERE Description = 'Neutro')
INSERT INTO Base_Shape SELECT (SELECT TOP 1  IdBase FROM  Base WHERE Description = 'BlueFlex s/escatola' And [Order]=29),  (SELECT IdShape FROM Shape WHERE Description = 'H10')
INSERT INTO Base_Shape SELECT (SELECT TOP 1  IdBase FROM  Base WHERE Description = 'BlueFlex s/escatola' And [Order]=29),  (SELECT IdShape FROM Shape WHERE Description = 'Horma Ancha')
INSERT INTO Base_Shape SELECT (SELECT TOP 1  IdBase FROM  Base WHERE Description = 'BlueFlex s/escatola' And [Order]=29),  (SELECT IdShape FROM Shape WHERE Description = 'Evertido')
INSERT INTO Base_Shape SELECT (SELECT TOP 1  IdBase FROM  Base WHERE Description = 'BlueFlex s/escatola' And [Order]=29),  (SELECT IdShape FROM Shape WHERE Description = 'Recto')
INSERT INTO Base_Shape SELECT (SELECT TOP 1  IdBase FROM  Base WHERE Description = 'BlueFlex s/escatola' And [Order]=29),  (SELECT IdShape FROM Shape WHERE Description = 'Deportiva')
INSERT INTO Base_Shape SELECT (SELECT TOP 1  IdBase FROM  Base WHERE Description = 'BlueFlex s/escatola' And [Order]=29),  (SELECT IdShape FROM Shape WHERE Description = 'Florentina')
INSERT INTO Base_Shape SELECT (SELECT TOP 1  IdBase FROM  Base WHERE Description = 'BlueFlex s/escatola' And [Order]=29),  (SELECT IdShape FROM Shape WHERE Description = 'Canadiense')
INSERT INTO Base_Shape SELECT (SELECT TOP 1  IdBase FROM  Base WHERE Description = 'BlueFlex s/escatola' And [Order]=29),  (SELECT IdShape FROM Shape WHERE Description = 'H45')
INSERT INTO Base_Shape SELECT (SELECT TOP 1  IdBase FROM  Base WHERE Description = 'BlueFlex c/Esctola' And [Order]=30),  (SELECT IdShape FROM Shape WHERE Description = 'Neutro')
INSERT INTO Base_Shape SELECT (SELECT TOP 1  IdBase FROM  Base WHERE Description = 'BlueFlex c/Esctola' And [Order]=30),  (SELECT IdShape FROM Shape WHERE Description = 'Deportiva')
INSERT INTO Base_Shape SELECT (SELECT TOP 1  IdBase FROM  Base WHERE Description = '3D' And [Order]=28),  (SELECT IdShape FROM Shape WHERE Description = 'Neutro')
INSERT INTO Base_Shape SELECT (SELECT TOP 1  IdBase FROM  Base WHERE Description = '3D' And [Order]=28),  (SELECT IdShape FROM Shape WHERE Description = 'Deportiva')
INSERT INTO Base_Shape SELECT (SELECT TOP 1  IdBase FROM  Base WHERE Description = 'Polifibra' And [Order]=23),  (SELECT IdShape FROM Shape WHERE Description = 'Neutro')
INSERT INTO Base_Shape SELECT (SELECT TOP 1  IdBase FROM  Base WHERE Description = 'Polifibra' And [Order]=23),  (SELECT IdShape FROM Shape WHERE Description = 'H10')
INSERT INTO Base_Shape SELECT (SELECT TOP 1  IdBase FROM  Base WHERE Description = 'Polifibra' And [Order]=23),  (SELECT IdShape FROM Shape WHERE Description = 'Horma Ancha')
INSERT INTO Base_Shape SELECT (SELECT TOP 1  IdBase FROM  Base WHERE Description = 'Polifibra' And [Order]=23),  (SELECT IdShape FROM Shape WHERE Description = 'Deportiva')
INSERT INTO Base_Shape SELECT (SELECT TOP 1  IdBase FROM  Base WHERE Description = 'PPS' And [Order]=22),  (SELECT IdShape FROM Shape WHERE Description = 'Neutro')
INSERT INTO Base_Shape SELECT (SELECT TOP 1  IdBase FROM  Base WHERE Description = 'PPS' And [Order]=22),  (SELECT IdShape FROM Shape WHERE Description = 'H10')
INSERT INTO Base_Shape SELECT (SELECT TOP 1  IdBase FROM  Base WHERE Description = 'PPS' And [Order]=22),  (SELECT IdShape FROM Shape WHERE Description = 'Horma Ancha')
INSERT INTO Base_Shape SELECT (SELECT TOP 1  IdBase FROM  Base WHERE Description = 'PPS' And [Order]=22),  (SELECT IdShape FROM Shape WHERE Description = 'Evertido')
INSERT INTO Base_Shape SELECT (SELECT TOP 1  IdBase FROM  Base WHERE Description = 'PPS' And [Order]=22),  (SELECT IdShape FROM Shape WHERE Description = 'Recto')
INSERT INTO Base_Shape SELECT (SELECT TOP 1  IdBase FROM  Base WHERE Description = 'PPS' And [Order]=22),  (SELECT IdShape FROM Shape WHERE Description = 'Deportiva')
INSERT INTO Base_Shape SELECT (SELECT TOP 1  IdBase FROM  Base WHERE Description = 'PPS' And [Order]=22),  (SELECT IdShape FROM Shape WHERE Description = 'Florentina')
INSERT INTO Base_Shape SELECT (SELECT TOP 1  IdBase FROM  Base WHERE Description = 'PPS' And [Order]=22),  (SELECT IdShape FROM Shape WHERE Description = 'Canadiense')
INSERT INTO Base_Shape SELECT (SELECT TOP 1  IdBase FROM  Base WHERE Description = 'PPS' And [Order]=22),  (SELECT IdShape FROM Shape WHERE Description = 'H45')
INSERT INTO Base_Shape SELECT (SELECT TOP 1  IdBase FROM  Base WHERE Description = 'Talon reforzado' And [Order]=2),  (SELECT IdShape FROM Shape WHERE Description = 'Neutro')
INSERT INTO Base_Shape SELECT (SELECT TOP 1  IdBase FROM  Base WHERE Description = 'Talon reforzado' And [Order]=2),  (SELECT IdShape FROM Shape WHERE Description = 'H10')
INSERT INTO Base_Shape SELECT (SELECT TOP 1  IdBase FROM  Base WHERE Description = 'Talon reforzado' And [Order]=2),  (SELECT IdShape FROM Shape WHERE Description = 'Horma Ancha')
INSERT INTO Base_Shape SELECT (SELECT TOP 1  IdBase FROM  Base WHERE Description = 'Talon reforzado' And [Order]=2),  (SELECT IdShape FROM Shape WHERE Description = 'Evertido')
INSERT INTO Base_Shape SELECT (SELECT TOP 1  IdBase FROM  Base WHERE Description = 'Talon reforzado' And [Order]=2),  (SELECT IdShape FROM Shape WHERE Description = 'Recto')
INSERT INTO Base_Shape SELECT (SELECT TOP 1  IdBase FROM  Base WHERE Description = 'Talon reforzado' And [Order]=2),  (SELECT IdShape FROM Shape WHERE Description = 'Deportiva')
INSERT INTO Base_Shape SELECT (SELECT TOP 1  IdBase FROM  Base WHERE Description = 'Talon reforzado' And [Order]=2),  (SELECT IdShape FROM Shape WHERE Description = 'Florentina')
INSERT INTO Base_Shape SELECT (SELECT TOP 1  IdBase FROM  Base WHERE Description = 'Talon reforzado' And [Order]=2),  (SELECT IdShape FROM Shape WHERE Description = 'Canadiense')
INSERT INTO Base_Shape SELECT (SELECT TOP 1  IdBase FROM  Base WHERE Description = 'Talon reforzado' And [Order]=2),  (SELECT IdShape FROM Shape WHERE Description = 'H45')
INSERT INTO Base_Shape SELECT (SELECT TOP 1  IdBase FROM  Base WHERE Description = 'Talonera Móvil' And [Order]=24),  (SELECT IdShape FROM Shape WHERE Description = 'Neutro')
INSERT INTO Base_Shape SELECT (SELECT TOP 1  IdBase FROM  Base WHERE Description = 'Termoplástica' And [Order]=25),  (SELECT IdShape FROM Shape WHERE Description = 'Neutro')
INSERT INTO Base_Shape SELECT (SELECT TOP 1  IdBase FROM  Base WHERE Description = 'Talonera Gel Polimero' And [Order]=26),  (SELECT IdShape FROM Shape WHERE Description = 'Neutro')
INSERT INTO Base_Shape SELECT (SELECT TOP 1  IdBase FROM  Base WHERE Description = 'Triple Densidad' And [Order]=31),  (SELECT IdShape FROM Shape WHERE Description = 'Neutro')
INSERT INTO Base_Shape SELECT (SELECT TOP 1  IdBase FROM  Base WHERE Description = 'Triple Densidad' And [Order]=31),  (SELECT IdShape FROM Shape WHERE Description = 'H10')
INSERT INTO Base_Shape SELECT (SELECT TOP 1  IdBase FROM  Base WHERE Description = 'Triple Densidad' And [Order]=31),  (SELECT IdShape FROM Shape WHERE Description = 'Horma Ancha')
INSERT INTO Base_Shape SELECT (SELECT TOP 1  IdBase FROM  Base WHERE Description = 'Triple Densidad' And [Order]=31),  (SELECT IdShape FROM Shape WHERE Description = 'Evertido')
INSERT INTO Base_Shape SELECT (SELECT TOP 1  IdBase FROM  Base WHERE Description = 'Triple Densidad' And [Order]=31),  (SELECT IdShape FROM Shape WHERE Description = 'Recto')
INSERT INTO Base_Shape SELECT (SELECT TOP 1  IdBase FROM  Base WHERE Description = 'Triple Densidad' And [Order]=31),  (SELECT IdShape FROM Shape WHERE Description = 'Deportiva')
INSERT INTO Base_Shape SELECT (SELECT TOP 1  IdBase FROM  Base WHERE Description = 'Triple Densidad' And [Order]=31),  (SELECT IdShape FROM Shape WHERE Description = 'Florentina')
INSERT INTO Base_Shape SELECT (SELECT TOP 1  IdBase FROM  Base WHERE Description = 'Triple Densidad' And [Order]=31),  (SELECT IdShape FROM Shape WHERE Description = 'Canadiense')
INSERT INTO Base_Shape SELECT (SELECT TOP 1  IdBase FROM  Base WHERE Description = 'Triple Densidad' And [Order]=31),  (SELECT IdShape FROM Shape WHERE Description = 'H45')
